repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check
        language: unsupported
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: ruff format --check
        language: unsupported
        types: [python]
      - id: basedpyright-check
        name: basedpyright-check
        entry: basedpyright
        language: unsupported
        types: [python]

  - repo: builtin
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
